cmake_minimum_required(VERSION 3.24)
project(set_lockscreen_wallpaper VERSION 0.2.0 LANGUAGES C)

if (NOT CMAKE_C_STANDARD)
	set(CMAKE_C_STANDARD 99)
endif ()
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)


# lib
set(SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME ${PROJECT_NAME})
set(SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_SOURCE_LIST)

if (WIN32)
	list(APPEND SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_SOURCE_LIST
		src/${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}_win32.c)
else ()
	message(FATAL_ERROR
		"Unsupported platform: ${CMAKE_SYSTEM_NAME}.\n"
		"Supported: Windows.")
endif ()

add_library(${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}
	STATIC ${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_SOURCE_LIST})
add_library(${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}::${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}
	ALIAS ${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME})
target_include_directories(${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}
	PUBLIC include)
target_compile_definitions(${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME}
	PRIVATE $<$<CONFIG:Debug>:DEBUG>)


# cli
set(SET_LOCKSCREEN_WALLPAPER_MAIN_CLI_TARGET_NAME cli_${PROJECT_NAME})

add_executable(${SET_LOCKSCREEN_WALLPAPER_MAIN_CLI_TARGET_NAME}
	cli/main.c)
set_target_properties(${SET_LOCKSCREEN_WALLPAPER_MAIN_CLI_TARGET_NAME}
	PROPERTIES OUTPUT_NAME ${PROJECT_NAME})
target_link_libraries(${SET_LOCKSCREEN_WALLPAPER_MAIN_CLI_TARGET_NAME}
	PRIVATE ${SET_LOCKSCREEN_WALLPAPER_MAIN_LIB_TARGET_NAME})
