name: CI

on:
  push:
    branches: [ main ]
    paths: &ci_paths
      - 'include/**'
      - 'src/**'
      - 'cli/**'
      - 'CMakeLists.txt'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [ windows-latest ]
        cmake_version: [ 3.24.0, latest ]
        c_compiler: [ cl ]
        c_standard: [ '99', '23' ]

        exclude:
          - os: windows-latest
            c_compiler: cl
            c_standard: '23'

        include:
          - os: windows-latest
            cmake_version: 3.24.0
            c_compiler: cl
            c_standard: '17'

          - os: windows-latest
            cmake_version: latest
            c_compiler: cl
            c_standard: '17'

    runs-on: ${{ matrix.os }}

    env:
      SCCACHE_GHA_ENABLED: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows' && matrix.c_compiler == 'cl'

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ matrix.cmake_version }}
        if: matrix.cmake_version != 'latest'

      - name: Echo CMake version
        run: cmake --version

      - name: Configure CMake
        run: >
          cmake . -B build
          -G Ninja
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_C_STANDARD=${{ matrix.c_standard }}
          -DCMAKE_C_COMPILER_LAUNCHER=sccache

      - name: CMake Build
        run: cmake --build build --parallel